#pragma config(Sensor, dgtl6,  mobileGoalT,    sensorTouch)
#pragma config(Sensor, dgtl7,  driveTrainLE,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  driveTrainRE,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, greenLed,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, redLed,         sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  topArm,         sensorNone)
#pragma config(Sensor, I2C_2,  botArm,         sensorNone)
#pragma config(Motor,  port1,           driveR2,       tmotorNone, openLoop)
#pragma config(Motor,  port2,           driveR1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveL1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mobileGoalR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobileGoalL,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armTop,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armBotR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armBotL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveL2,       tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)


#pragma competitionControl(Competition)


#include "Vex_Competition_Includes.c"

#include "LazyPeopleFunctions.h"

#define mobileGoal motor[mobileGoalR] = motor[mobileGoalL]

#define redLEDon SensorValue[redLed] = 1;

#define redLEDoff SensorValue[redLed] = 0;

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

int matchAuto = 2;

// 0 = skills: 1 = 5 point MG: 2 = 10 point MG:

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



task autonomous()
{

	if(matchAuto == 1)
	{
		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;


		motor[claw2] = 20;

		delay(100);

		motor[claw2] = 0;

		delay(100);

		motor[armTop] = 127;
		motor[armBotL] = 127;
		motor[armBotR] = 127;

		delay(200);

		motor[armBotL] = 0;
		motor[armBotR] = 0;

		delay(400);

		motor[armTop] = 10;

		motor[mobileGoalL] = 127;
		motor[mobileGoalR] = 127;

		delay(650);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		while(SensorValue[mobileGoalT] == 0)
		{
			motor[driveL1] = 127;
			motor[driveR1] = 127;
		}

		delay(50);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		motor[mobileGoalL] = -127;
		motor[mobileGoalR] = -127;

		delay(200);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;


		delay(500);


		motor[driveL1] = 0;
		motor[driveR1] = 0;

		motor[mobileGoalL] = -127;
		motor[mobileGoalR] = -127;

		delay(750);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		delay(100);

		motor[armTop] = 127;

		delay(200);

		motor[armTop] = 0;

		//motor[claw2] = -127;

		//delay(200);

		//motor[claw2] = 0;

		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;


		while(SensorValue[driveTrainLE] < 850)
		{
			motor[driveL1] = -127;
			motor[driveR1] = -127;
		}

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;



		motor[driveL1] = 127;
		motor[driveR1] = -127;

		delay(1250);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		delay(200);

		motor[claw2] = -127;
		motor[armTop] = 127;

		delay(200);

		motor[claw2] = 0;

		delay(400);

		motor[armTop] = 10;

		delay(400);

		motor[driveL1] = 127;
		motor[driveR1] = 127;

		//delay(500);

		motor[mobileGoalR] = 127;

		delay(500);
		//delay(500);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		//motor[mobileGoalL] = 127;

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		motor[driveL1] = -127;
		motor[driveR1] = -127;

		delay(1000);

		motor[driveL1] = 0;
		motor[driveR1] = 0;
	}

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	else if(matchAuto == 2)
	{
		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;


		motor[claw2] = 20;

		delay(100);

		motor[claw2] = 0;

		delay(100);

		motor[armTop] = 127;
		motor[armBotL] = 127;
		motor[armBotR] = 127;

		delay(200);

		motor[armBotL] = 0;
		motor[armBotR] = 0;

		delay(400);

		motor[armTop] = 10;

		motor[mobileGoalL] = 127;
		motor[mobileGoalR] = 127;

		delay(650);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		while(SensorValue[driveTrainLE] < 1450 || SensorValue[driveTrainRE] < 1450)
		{
			if(SensorValue[driveTrainLE] < 1450)
			{
				motor[driveL1] = 127;
			}
			if(SensorValue[driveTrainRE] < 1450)
			{
				motor[driveR1] = 127;
			}
		}

		delay(50);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		motor[mobileGoalL] = -127;
		motor[mobileGoalR] = -127;

		delay(200);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;


		delay(500);


		motor[driveL1] = 0;
		motor[driveR1] = 0;

		motor[mobileGoalL] = -127;
		motor[mobileGoalR] = -127;

		delay(750);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		delay(100);

		motor[armTop] = 127;

		delay(200);

		motor[armTop] = 0;

		//motor[claw2] = -127;

		//delay(200);

		//motor[claw2] = 0;

		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;


		while(SensorValue[driveTrainLE] < 850)
		{
			motor[driveL1] = -127;
			motor[driveR1] = -127;
		}

		delay(100);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;



		motor[driveL1] = 127;
		motor[driveR1] = -127;

		delay(1400);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		delay(200);

		motor[claw2] = -127;
		motor[armTop] = 127;

		delay(200);

		motor[claw2] = 0;

		delay(400);

		motor[armTop] = 10;

		delay(400);

		motor[driveL1] = 127;
		motor[driveR1] = 127;

		delay(800);

		motor[driveR1] = 80;

		delay(400);

		motor[mobileGoalR] = 127;
		motor[mobileGoalL] = 127;

		delay(300);
		//delay(500);

		//motor[driveL1] = 0;
		//motor[driveR1] = 0;

		//motor[mobileGoalL] = 127;

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		motor[driveL1] = -127;
		motor[driveR1] = -127;

		delay(1000);

		motor[driveL1] = 0;
		motor[driveR1] = 0;


	}

	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	else
	{

		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;


		motor[claw2] = 20;

		delay(100);

		motor[claw2] = 0;

		delay(100);

		motor[armTop] = 127;
		motor[armBotL] = 127;
		motor[armBotR] = 127;

		delay(200);

		motor[armBotL] = 0;
		motor[armBotR] = 0;

		delay(400);

		motor[armTop] = 10;

		motor[mobileGoalL] = 127;
		motor[mobileGoalR] = 127;

		delay(650);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		while(SensorValue[mobileGoalT] == 0)
		{
			motor[driveL1] = 127;
			motor[driveR1] = 127;
		}

		delay(100);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		motor[mobileGoalL] = -127;
		motor[mobileGoalR] = -127;

		delay(200);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;


		delay(500);


		motor[driveL1] = 0;
		motor[driveR1] = 0;

		motor[mobileGoalL] = -127;
		motor[mobileGoalR] = -127;

		delay(750);

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		delay(100);

		motor[armTop] = 127;

		delay(200);

		motor[armTop] = 0;



		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;


		while(SensorValue[driveTrainLE] < 850)
		{
			motor[driveL1] = -127;
			motor[driveR1] = -127;
		}

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		SensorValue[driveTrainLE] = 0;
		SensorValue[driveTrainRE] = 0;

		Gerald = 1;

		motor[driveL1] = 127;
		motor[driveR1] = -127;

		delay(1400);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		delay(200);

		motor[claw2] = -127;
		motor[armTop] = 127;

		delay(200);

		motor[claw2] = 0;

		delay(400);

		motor[armTop] = 10;

		//delay(400);

		//autoStack();

		//autoStack();

		//autoStack();

		//autoStack();

		//autoStack();

		////This won't work first try.

		//motor[driveL1] = 127;
		//motor[driveR1] = -127;

		//delay(600);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		delay(400);

		motor[driveL1] = 127;
		motor[driveR1] = 127;

		delay(1000);

		motor[mobileGoalR] = 127;

		delay(500);
		//delay(500);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

		//motor[mobileGoalL] = 127;

		motor[mobileGoalL] = 0;
		motor[mobileGoalR] = 0;

		motor[driveL1] = -127;
		motor[driveR1] = -127;

		delay(1000);

		motor[driveL1] = 0;
		motor[driveR1] = 0;

	}

}



task usercontrol()
{

	int armHold;
	int clawHold;
	//int buttonPressed = 0;
	int Swensons;
	Swensons = 0;
	Gerald = 0;

	while (true)
	{

		//making the drive train move with the joysticks
		//motor[driveR1] = vexRT[Ch2];
		//motor[driveL1] = vexRT[Ch3];
		//Experimental Code Start
		/*
		if(vexRT[Btn8R] == 1 && Swensons == 0 && buttonPressed == 0)
		{
		buttonPressed = 1;
		Swensons = 1;
		}
		else if(vexRT[Btn8R] == 1 && Swensons == 1 && buttonPressed == 0)
		{
		buttonPressed = 1;
		Swensons = 0;
		}
		else if(vexRT[Btn8R] == 0)
		{
		buttonPressed = 0;
		}

		switch(Swensons)
		{
		case 1:
		motor[driveR1] = vexRT[Ch2]*-1;
		motor[driveL1] = vexRT[Ch3]*-1;

		SensorValue[greenLed] = 1;
		SensorValue[redLed] = 0;
		break;

		default:
		*/
		//motor[driveR1] = motor[driveR2] = vexRT[Ch2];
		//motor[driveL1] = motor[driveL2] = vexRT[Ch3];

		drive();

		SensorValue[greenLed] = 0;
		SensorValue[redLed] = 1;
		//	}


		//allows driver to switch between forwards and backwards driving
		// YEET! not anymore.

		//Experimental Code end */

		if(vexRT[Btn6U] == 1)
		{
			//armMotors = 127;
			armHold = 1;
			motor[armTop] = 100;
			//motor[armBot] = 127;

		}

		else if(vexRT[Btn6D] == 1)
		{
			//armMotors = -20;
			armHold = 0;
			motor[armTop] = -100;
			//motor[armBot] = -50;
		}

		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0 && armHold == 1)
		{
			//armMotors = 15;
			motor[armTop] = 20;
			//motor[armBot] = 10;
		}

		else if(vexRT[Btn6U] == 0 && vexRT[Btn6D] == 0 && armHold == 0)
		{
			//armMotors = 15;
			motor[armTop] = -20;
			//motor[armBot] = 10;
		}


		//raises and lowers the extension mechanism
		if(vexRT[Btn5U] == 1)
		{
			//clawMotors = 127;
			motor[claw2] = 63;
			clawHold = 1;
		}

		else if(vexRT[Btn5D] == 1)
		{
			//clawMotors = -127;
			motor[claw2] = -63;
			clawHold = 0;
		}
		/*
		else if(vexRT[Btn5D] == 0 && (vexRT[Btn5U]) == 0 && clawHold == 1)
		{
		motor[claw2] = 63;
		}
		*/
		else
		{
			//clawMotors = 0;
			motor[claw2] = 0;
		}

		autoStack();


		//open and closes the claw
		/*	if(vexRT[Btn8U] == 1)
		{
		//extender = 127;
		motor[extendL] = 127;
		}

		else if(vexRT[Btn8D] == 1)
		{
		//extender = -127;
		motor[extendL] = -127;
		}
		else
		{
		//extender = 0;
		motor[extendL] = 0;
		}
		*/
		//extends claw in and out

		if(vexRT[Btn7U] == 1)
		{
			mobileGoal = 127;
			//motor[mobileGoalL] = 127;
			//motor[mobileGoalR] = 127;
		}

		else if(vexRT[Btn7D] == 1)
		{
			mobileGoal = -127;
			//motor[mobileGoalL] = -127;
			//motor[mobileGoalR] = -127;
		}

		else
		{
			mobileGoal = 0;
			//motor[mobileGoalL] = 0;
			//motor[mobileGoalR] = 0;
		}

		if(vexRT[Btn8U] == 1)
		{
			motor[armBotL] = 127;
			motor[armBotR] = 127;
		}

		else if(vexRT[Btn8D] == 1)
		{
			motor[armBotL] = -127;
			motor[armBotR] = -127;
		}

		else
		{
			motor[armBotL] = 10;
			motor[armBotR] = 10; //Changed from 10 to 0.
		}

		if(vexRT[Btn7R] == 1)
		{
			SensorValue[driveTrainLE] = 0;
			SensorValue[driveTrainRE] = 0;
		}


		/*

		if(vexRT[Btn7R] == 1)
		{
		motor[armTop] = 127;
		motor[armBotR] = 127;
		motor[armBotL] = 127;

		delay(500);

		motor[armTop] = 0;
		motor[armBotR] = 0;
		motor[armBotL] = 0;
		motor[claw2] = -127;

		delay(100);

		motor[claw2] = 0;

		delay(100);

		motor[armBotR] = -127;
		motor[armBotL] = -127;
		motor[armTop] = -127;

		delay(500);

		motor[armBotR] = 0;
		motor[armBotL] = 0;
		motor[armTop] = 0;
		}

		*/
		//EXPERIMENTAL CODE
		SensorValue[greenLed] = 1;
		SensorValue[redLed] = 1;
		/*
		if(vexRT[Btn8L] == 1)
		{
		Swensons = 1;
		}
		if(vexRT[Btn8R])
		{
		Swensons = 2;
		}
		*/
		//moves mobile goal snatcher in and out
	}
}



/*
programming notes:
contact for help:
name is Mike Ison
michael.ison@gmail.com
program helps you talk to a machine
best book for c "The C programming guide"
BEING TAUGHT C not robot c
robot c uses c
for self teaching use www.learn-c.org
compiler to run normal c files. www.onlinegdb.com/online_c_compiler

does whatever is inside of it till its argument is false
break stops a loop
continue starts new loop(skips all code after it)
do while loop does its code then checks it condition(never used)
array is a list of things
motors and buttons are arrays
encoders and sensors are arrays
robot c is an interface that sits on top of c
*/
