#pragma config(Motor,  port2,           mobileGoal1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveR1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveL1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           extendL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           extendR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armRU,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armLU,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw1,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define t true;

#define f false;

#define driveR motor[driveR1]

#define driveL motor[driveL1]

#define clawMotors motor[claw1]

#define armMotors motor[armLU] = motor[armRU]

#define extender motor[extendR] = motor[extendL]

#define mobileGoal motor[mobileGoal1]

#pragma platform(VEX2)


#pragma competitionControl(Competition)


#include "Vex_Competition_Includes.c"


void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{






	AutonomousCodePlaceholderForTesting();
}





task usercontrol()
{

	while (true)
	{
		motor[driveR] = vexRT[Ch2];
		motor[driveL] = vexRT[Ch3];
		//making the drive train move with the joysticks
		if(SensorValue(vexRT[Btn5U]) == 1)
		{
			armMotors = 127;

		}
		else if(SensorValue(vexRT[Btn5D]) == 1)
		{
			armMotors = -20;
		}
		else
		{
			armMotors = 15;
		}
		//raises and lowers the extension mechanism
		if(SensorValue(vexRT[Btn6U]) == 1)
		{
			clawMotors = 127;
		}
		else if(SensorValue(vexRT[Btn6D]) == 1)
		{
			clawMotors = -127;
		}
		else
		{
			clawMotors = 0;
		}
		//open and closes the claw
		if(SensorValue(vexRT[Btn8U]) == 1)
		{
			extender = 127;
		}

		else if(SensorValue(vexRT[Btn8D]) == 1)
		{
			extender = -127;
		}
		else
		{
			extender = 0;
		}
		//extends claw in and out
		if(SensorValue(vexRT[Btn7U]) == 1)
		{
			mobileGoal = 127;
		}
		else if(SensorValue(vexRT[Btn7D]) == 1)
		{
			mobileGoal = -127;
		}

		else
		{
			mobileGoal = 0;
		}
		//moves mobile goal snatcher in and out
	}
}

/*
programming notes:
contact for help:
name is Mike Ison
michael.ison@gmail.com
program helps you talk to a machine
best book for c "The C programming guide"
BEING TAUGHT C not robot c
robot c uses c
for self teaching use www.learn-c.org
compiler to run normal c files. www.onlinegdb.com/online_c_compiler

does whatever is inside of it till its argument is false
break stops a loop
continue starts new loop(skips all code after it)
do while loop does its code then checks it condition(never used)
array is a list of things.
motors and buttons are arrays
encoders and sensors are arrays
robot c is an interface that sits on top of c
*/
